name: build
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - id: set-matrix
      shell: pwsh
      run: |
        $config=Get-Content -Path ./config.json
        echo "matrix=$config" >> $env:GITHUB_OUTPUT
  execute:
    needs: init
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.init.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.id }}
