name: build
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      shell: pwsh
      run: Write-Host "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $env:GITHUB_OUTPUT
  execute:
    needs: init
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.init.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}
